# -*- Mode: python; py-indent-offset: 4; indent-tabs-mode: nil; coding: utf-8; -*-

# def options(opt):
#     pass

# def configure(conf):
#     conf.check_nonfatal(header_name='stdint.h', define_name='HAVE_STDINT_H')
import os
def build(bld):
    module = bld.create_ns3_module('ipv6-transition', ['internet'])
    module.source = [
		'helper/ipv6-transition-address-generator.cc',
		'model/dualstack-container.cc',
		'model/ipv6-encapsulation-header.cc',
		'model/transition-6in4.cc',
		'model/transition-6rd.cc',
        ]

    module_test = bld.create_ns3_module_test_library('ipv6-transition')
    module_test.source = [
        'test/ipv6-transition-test-suite.cc',
        ]

    headers = bld(features='ns3header')
    headers.module = 'ipv6-transition'
    headers.source = [
		'helper/ipv6-transition-address-generator.h',
		'model/dualstack-container.h',
		'model/ipv6-encapsulation-header.h',
		'model/transition-6in4.h',
		'model/transition-6rd.h',
        ]

#    if bld.env.ENABLE_EXAMPLES:
#    if os.environ['TRANSITION'] == '1':
    bld.recurse('examples')

    # bld.ns3_python_bindings()
